package creditcard.gui;/*
		A basic implementation of the JDialog class.
*/

import creditcard.account.ProxyCreditCardAccount;
import framework.account.AbstractAccount;
import framework.account.Account;
import framework.controller.AccountController;
import framework.service.AccountService;

import java.awt.*;
import java.util.List;
import javax.swing.*;

public class JDialogGenBill extends javax.swing.JDialog
{
    String billstring;
    
	public JDialogGenBill(Frame parent)
	{
		super(parent);
		setTitle("Generated Monthly Bills");
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parses  your Java file into its visual envirenment. 
		//{{ INIT_CONTROLS 
		getContentPane().setLayout(null);
		setSize(405,367);
		setVisible(false);
		getContentPane().add(JScrollPane1);
		JScrollPane1.setBounds(24,24,358,240);
		JScrollPane1.getViewport().add(JTextArea1);
		JTextArea1.setBounds(0,0,355,237);

		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(156,276,96,24);

		// generate the string for the monthly bill

		JTextArea1.setText(printBills());
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
		//}}
	}

	public JDialogGenBill()
	{
		this((Frame)null);
	}



	//{{DECLARE_CONTROLS
	javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();
	javax.swing.JTextArea JTextArea1 = new javax.swing.JTextArea();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event)
	{
		dispose();
			 
	}

	protected String printBills() {
		String billstring ="";
		AccountController auc = new AccountController(new AccountService());
		List<Account> accounts = auc.getAllAccounts();
		//System.err.println(accounts.toString());
		for (AbstractAccount acc : accounts) {
			if (acc != null) {
				ProxyCreditCardAccount pacc = new ProxyCreditCardAccount(acc);
				System.err.println("JDialogGenBill Proxy\t"+pacc.toString());

				pacc.generateMonthlyBillingReport();

				billstring += "Name = "+pacc.getUser().getName()+"\r\n";
				billstring += "Address= "+pacc.getUser().getStreet()+"\r\n";
				billstring += "CC number= "+pacc.getAccountNbr()+"\r\n";
				billstring += "CC type= "+pacc.getAccTypes()+"\r\n";
				billstring += pacc.generateMonthlyBillingReport();
//				billstring += "Previous balance = $ "+pacc.getLastMonthBalance()+"\r\n";
//				billstring += "Total Credits = $ "+pacc.getTotalMonthlyCredits()+"\r\n";
//				billstring += "Total Charges = $ "+pacc.getMonthlyAmountDue()+"\r\n";
				billstring += "New balance = $ "+pacc.getNewMonthlyBalance()+"\r\n";
				billstring += "Total amount due = $ "+pacc.getMonthlyAmountDue()+"\r\n";
				billstring += "\r\n";
				billstring += "\r\n";


			}
		}

		return billstring;

	}
}
